// Generated by CoffeeScript 1.6.3
module("Dropbox Binary Test");

test("Auto Login(8s)", function() {
  stop();
  return setTimeout(function() {
    if (!Nimbus.Auth.authorized()) {
      localStorage.clear();
      return Nimbus.Auth.authorize("Dropbox");
    } else {
      deepEqual(Nimbus.Auth.authorized(), true, "have  been  login");
      return start();
    }
  }, 8000);
});

test("Upload binary file(10s)", function() {
  stop();
  setTimeout(function() {
    var finput;
    finput = document.getElementById("file_upload");
    window.f1 = finput.files[0];
    return Nimbus.Binary.upload_file(window.f1, function(file) {
      return window.f2 = file;
    });
  }, 4000);
  return setTimeout(function() {
    return Nimbus.Client.Dropbox.getMetadataList("/" + window.f1.name, function(data) {
      deepEqual(1, 1, "have  been  added");
      return start();
    }, function(err) {
      deepEqual(0, 1, "have  been  added");
      return start();
    });
  }, 10000);
});

test("delete this binary file(10s)", function() {
  stop();
  setTimeout(function() {
    Nimbus.Binary.delete_file(window.f2);
    return binary.find(window.f2.id).destroy();
  }, 5000);
  return setTimeout(function() {
    return Nimbus.Client.Dropbox.getMetadataList("/" + window.f1.name, function(data) {
      deepEqual(0, 1, "have  been  deleted");
      return start();
    }, function(err) {
      deepEqual(1, 1, "have  been  deleted");
      return start();
    });
  }, 10000);
});
